name: freelance_companion
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  intl: ^0.20.2
  supabase_flutter: ^2.10.3
  shared_preferences: ^2.0.18
  uuid: ^4.5.1
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
